name: Flask CI/CD

on:
  push:
    branches:
      - main
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Build Flask Image
      run: |  
        docker build -t myflaskapp:${{ github.sha }} .
        
    - name: Deploy to Minikube
      uses: docker://bitnami/kubectl:latest
      env:
        KUBECONFIG: ~/.kube/config
      run: |
        kubectl apply -f flask-deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/my-deployment
        
  test:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Test Flask App
      run: |
        pip install pytest
        pytest tests